
package glossaire;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agnes extends ruben
 */
/*
            Faire une petit soft permettant de crée
                                               lire
                                               mettre à jour
                                               supprimer 
            CRUD
            Un glossaire contenant diverses informations 
            un mot sa définitions etc etc 
            Premierement on place notre mot dans un premier text area 
            Deuxiemement on place notre definiton dans un second text
            et enfin lors du clique sur le bouton envoie on recupere les deux 
            saisis et on les envoie dans la base de donnée 
        */
public class Vue extends javax.swing.JFrame {
    Lexique lexique = new Lexique();
    DefaultTableModel modelTab;
    /**
     * Creates new form Vue
     */
    public Vue() {
        initComponents();
        modelTab = (DefaultTableModel) motAndLang.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane selector = new javax.swing.JTabbedPane();
        javax.swing.JPanel create = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        motArea = new javax.swing.JTextArea();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        definitionArea = new javax.swing.JTextArea();
        javax.swing.JButton envoieBtn = new javax.swing.JButton();
        javax.swing.JLabel motLabel = new javax.swing.JLabel();
        javax.swing.JLabel definitionLabel = new javax.swing.JLabel();
        javax.swing.JPanel read = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        afficheArea = new javax.swing.JTextArea();
        javax.swing.JLabel afficheLabel = new javax.swing.JLabel();
        afficheBtn = new javax.swing.JButton();
        javax.swing.JScrollPane listeMot = new javax.swing.JScrollPane();
        motAndLang = new javax.swing.JTable();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel update = new javax.swing.JPanel();
        javax.swing.JPanel delete = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("glossaire");
        setResizable(false);

        selector.setToolTipText("");
        selector.setName(""); // NOI18N

        motArea.setColumns(20);
        motArea.setRows(5);
        jScrollPane1.setViewportView(motArea);

        definitionArea.setColumns(20);
        definitionArea.setRows(5);
        jScrollPane2.setViewportView(definitionArea);

        envoieBtn.setText("Envoie");
        envoieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoieBtnActionPerformed(evt);
            }
        });

        motLabel.setText("Mot");

        definitionLabel.setText("Definition");

        javax.swing.GroupLayout createLayout = new javax.swing.GroupLayout(create);
        create.setLayout(createLayout);
        createLayout.setHorizontalGroup(
            createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createLayout.createSequentialGroup()
                        .addComponent(envoieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(321, 321, 321))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createLayout.createSequentialGroup()
                        .addComponent(definitionLabel)
                        .addGap(350, 350, 350))))
            .addGroup(createLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(motLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createLayout.setVerticalGroup(
            createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(motLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(definitionLabel)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(envoieBtn)
                .addGap(50, 50, 50))
        );

        selector.addTab("Create", create);

        afficheArea.setColumns(20);
        afficheArea.setRows(5);
        jScrollPane3.setViewportView(afficheArea);

        afficheLabel.setText("Liste de mots");

        afficheBtn.setText("Affiche");
        afficheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficheBtnActionPerformed(evt);
            }
        });

        motAndLang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mot", "Langage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        motAndLang.setAutoscrolls(false);
        motAndLang.setColumnSelectionAllowed(true);
        motAndLang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                motAndLangMouseClicked(evt);
            }
        });
        listeMot.setViewportView(motAndLang);
        motAndLang.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (motAndLang.getColumnModel().getColumnCount() > 0) {
            motAndLang.getColumnModel().getColumn(0).setResizable(false);
            motAndLang.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("Définitions");

        javax.swing.GroupLayout readLayout = new javax.swing.GroupLayout(read);
        read.setLayout(readLayout);
        readLayout.setHorizontalGroup(
            readLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(afficheLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(127, 127, 127))
            .addGroup(readLayout.createSequentialGroup()
                .addComponent(listeMot, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(readLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(afficheBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        readLayout.setVerticalGroup(
            readLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(afficheBtn)
                .addGap(18, 18, 18)
                .addGroup(readLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afficheLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(readLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(listeMot, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        selector.addTab("Read", read);

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        selector.addTab("Update", update);

        javax.swing.GroupLayout deleteLayout = new javax.swing.GroupLayout(delete);
        delete.setLayout(deleteLayout);
        deleteLayout.setHorizontalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        deleteLayout.setVerticalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        selector.addTab("Delete", delete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selector)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selector, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        selector.getAccessibleContext().setAccessibleName("Create");

        getAccessibleContext().setAccessibleName("Glossaire");
        getAccessibleContext().setAccessibleDescription("Definition de mot");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    /*
         * Recuperere les infos stocker dans les text area
         * Ouvre la connection vers le serveur sql
         * Insertion des éléménts dans la table correspondante
         * INSERT INTO ma_table(colone
         */
 
    
    private void envoieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoieBtnActionPerformed
        //TODO lors du clique on Recupere les info dans les texte area et on les envoie dans la bdd
        

        
    }//GEN-LAST:event_envoieBtnActionPerformed

    private void afficheBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficheBtnActionPerformed
        // TODO Lors du clic affiche les élément de la table lexique dans le tableau 
       // afficheArea.setText(Lexique.afficheEnsemble().toString()); //Affiche avec le toString
       
        ArrayList<Lexique> array = ModeleLexique.afficheEnsemble();
       System.out.println(array);
//       
//       for(Lexique l : array){
//        modelTab.addRow(l.toArray());
//        }
    }//GEN-LAST:event_afficheBtnActionPerformed

    private void motAndLangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motAndLangMouseClicked
        // TODO add your handling code here:
        afficheArea.setLineWrap(true);
        afficheArea.setText(ModeleLexique.afficheDefinition());
        
    }//GEN-LAST:event_motAndLangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vue().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextArea afficheArea;
    javax.swing.JButton afficheBtn;
    javax.swing.JTextArea definitionArea;
    javax.swing.JTable motAndLang;
    javax.swing.JTextArea motArea;
    // End of variables declaration//GEN-END:variables
}
